# Funding
# Support this project by sending funds to GitHub Sponsor below.

github: farhnkrnapratma

# DISCLAIMER: This sponsorship is a VOLUNTARY CONTRIBUTION to support the
#             continued development of an OPEN-SOURCE PROJECT. It is NOT A
#             COMMERCIAL TRANSACTION, and NO GOODS OR SERVICES ARE EXCHANGED.
#             CONTRIBUTIONS CANNOT BE REFUNDED FOR ANY REASON
